language: node_js
node_js:
- '4.1'
sudo: false
addons:
  apt:
    packages:
    - sshpass
cache:
  directories:
  - node_modules
script:
- npm install -g gulp
- npm install -g codeclimate-test-reporter
- gem install scss_lint
- npm update
- gulp dist
after_success:
- |
  if [ $TRAVIS_PULL_REQUEST == "false" ] ; then
    export SSHPASS=$DEPLOY_PASS
    ssh-keyscan -t rsa $DEPLOY_HOST >> ~/.ssh/known_hosts
    sshpass -e rsync -aP dist/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$TRAVIS_BRANCH
  fi
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: cuRCUcPs6DhGSnRr8IeAQ1KcTMMqp/DwoFfLe7MJTiMFLkv0qp723ONoh9Iao+ydecQI6eCNlVbBoPcXkpM39KZtIuJuVjNcEej5jhZf9MO44kEHnoNwbiSEEVzl8Maoqnmwjii3ApJVal6WyMrqBxWzvvmb/UgABpfoSa4NYwk49hHnT7gH4hBwklJ8jqgXgWcuv9tpFMTcJzdVGycNzHPrL034hcqQ0lx75l9UJ0o/Ykms29KJFLa6hpWY9b25WngQzORyNd4ZULZxuGBpu5sEqNXxq4UpgdTkyuP4t5o3fIdWqhgaFodgs1jCjY062U1bdFvM9m1DDTiP5qNKckUDWuBqpEbzphHXg42exEExwDOyNyjp6KSNe5XS4B3c70W9ZQjhHDBYR/wBT8HZj4JVV+3NHH39imNEqLsTOlXgk6sSh90icZPaOVYKAURnu4ZD7cqkOhprxnTpRTPBNZyI858JAqkTl2JyFryFOixv3KYuArpVWrqEmQyguGCeTHhmzMMwy5gT+bLZ0sfjTvcH2NNFXcySDGZegfp9dzQScbEQhy15SXKMjqzqu3fX1p7JDiLULhubDZQv+/XvLibPtmr8IN1bDRJU8TphGpIwTEzWgXDgJY6Flc2tEBqhaZB33Fro+TeZajqqGP3qWAkskggsx8J8npaBc4vZoDo=
  - secure: WHw1WCzCqCdnptBF0hgMWcdadTnRggu9OTnUgk8jZw44VEB2uz6tWJ4bHnFIIKZA9i2VQsGHoRy1Qf+k3pQ3iviqtF/k27JSlu2HN8df4Uh+WImO4B5gNLU++5zXFR4Ij4ldCMY0eWGuWeUNxK6RZ47vHsKeWyIr2Eit7/7dNiJEJvhpXJa90bexpFhNF0k1o0vJRf9tmE1R+womBqPW2Nmv1zoNdlZmNsiPqfpzmmtsKzRw9gELZYO0qXY0gfulKoJe+1497U8nyLbbCLmnu1oN/W5Wign2JMEgE5KMa66vXUWlLEI9xCaEZf7ZgYHBndDIq4I2CAaC4QffLz08JS+XHSdhM6Nm8ipH6vcfHPQrKccGltXBU9dq+ucmPYrdTMiS+FNedgsJ2U0sRkJWeXkLgJ2INdwsWEBfIoGFVFtw76ro+07Qj5nWYI5U2Hqy1sypKm2S3qgr5PrOaduFGWKGvZdz3uSL5Hx5BzCyE3gnY/ItoBhG+oYYkUmU8uCv39XHcEXr1i3d8ioG6OilHXaDl6L4/SvPgnyUJ/0YJA8RqOX6dstVs5vvAUqlqzeYoks9TJXBq0yhHOZ5fwR6ipJhChT0w0CA/LOdP/+nHp3KmHLJaK4qYAf3FCSks4lNQlPMxdAeFkHNo2dqTE1frdKCdrjuvVmOF4BhAlrIAwY=
  - secure: NNOtRbV0I02tjigZD97WBIq+vgZlNbW0PVv78kQ0Tm8ITAb/zTeLoh5gJ/etaRV7hwYxFfvN2XF0uOyaZSZmiHiFwUdwvnqtCNBqoQrV4NjZzf6NMR7GGgjsehogGOxj87aX6c8FI/qiDgSHvCj9GXr7KeWCfBpi+J/vb/oRxi4cwMxNLDUgwXqz9PWaEK3AGBDWIsle5LxNOVtuBxM694WfpJnaS0b7noqeft67D+dedoQo2fbia5PeGqyrkoxlOT01g98Aw82rE2kQoAGL69X8AWppYUMiYcTVHb4IafKSF44HMx88umi9f32uSnCbm4NV+VLuy9A4bbUCUXzaiuUpLH7jY0zK1+V2aNlyGUSd51QzgpmIxua+KHQzsVujSk2HDJoiPWy+dE7qKIDGHMdbGBkfAUOrJvz6rgWkpSpyDcQBT2su6y8fUkHKtKxWNeJghwZzmumonLSa5jyMkMiSY6MvPolPg+elnn+kb+M9BlIWGqsSiXHZ9pQp2untmxnLA4SG1ufFXCBLUQvlxz0v83BiVfIAfNEs8DiRLD5BigOVFQ4W3DqCRODzVoeGicO3uxoyPgqCxtuB9XYukjXBhTNhqfoMyss9+zWwBqJM1Mpg9xcsxSIcJa99wefF50nWKlkzDt3H6xzGcDDIJp1GigC6CDE3D2Tc6r4/8W8=
  - secure: i71traC/32NWPe9a/8niCv6ZQI9wngi5tWufhpZ5qHGOcs15We+Wi2c3/QdKRYqpngY1QFbrlYwv64feKo6wfknD0MgMKMgf7Z5WLy0YRKuitvi7+W+ujlK9Oc1EiUO+4eCknVVZZTnN/PsVXKnnbj/uDdMg99i0gtJAalJ20QjNELDTSIY9yTf51F7OfnZQrO9qceKisWyKfdgradfxLiN6q1enUVxpUso9O74LEYNjT47Z+ZrDm79YYhWYDH40vl9ZBZu66mYLpB7NjOO39s27BM2roFsdLXC7H+CXRMTUmfWejM8LrowtO5tUo1YyL9mY96rN2AnsK1VAwhUX53mNr0cUgAF9xitWdlgkZVTcher9BMZqCHB3HP59v8JFgXHZw3w5KkE6F0lklRcFkkvXnN/ksyrtwjWg4lmRHycPcjPogd1NKA2dl2yYbkDTYWsA5j/reLBdcCoQq+u09Ynzu7q+fN4ZuuxUD44xNn8LDLsnw1h/dGfZ3nsWJw+IvwpjojGrPIqmoLnMK6xk7Bt48vP6eE6onPIBC6BmkqUEH7H9aDwdhDMSNA81J9d8kXvcF03gcGtr8yCJ82fHun+KiGf/nAB5MkPHsTqUuY6zooBSAGs3A/F+a2Rey5WFO1FQ0URoE6V1i8GKQwUosG3OXxar/NQFNwfuQ4BtKfU=
